spring:
  application:
    name: sb-1

  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: springuser
    password: springpass
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql;
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


